/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.edgecloudmodel.eCModel.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.edgecloudmodel.eCModel.CollectionTypeIdentifierCS;
import org.xtext.example.edgecloudmodel.eCModel.ECModelPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Collection Type Identifier CS</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class CollectionTypeIdentifierCSImpl extends ReservedKeywordCSImpl implements CollectionTypeIdentifierCS
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CollectionTypeIdentifierCSImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ECModelPackage.Literals.COLLECTION_TYPE_IDENTIFIER_CS;
  }

} //CollectionTypeIdentifierCSImpl
