/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.edgecloudmodel.eCModel.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.edgecloudmodel.eCModel.ComplexOpeartion;
import org.xtext.example.edgecloudmodel.eCModel.ECModelPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Complex Opeartion</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ComplexOpeartionImpl extends WorkflowExpImpl implements ComplexOpeartion
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ComplexOpeartionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ECModelPackage.Literals.COMPLEX_OPEARTION;
  }

} //ComplexOpeartionImpl
