/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.edgecloudmodel.eCModel.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.edgecloudmodel.eCModel.ECModelPackage;
import org.xtext.example.edgecloudmodel.eCModel.JoinExp;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Join Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class JoinExpImpl extends MinimalEObjectImpl.Container implements JoinExp
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected JoinExpImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ECModelPackage.Literals.JOIN_EXP;
  }

} //JoinExpImpl
