/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.edgecloudmodel.eCModel.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.edgecloudmodel.eCModel.ECModelPackage;
import org.xtext.example.edgecloudmodel.eCModel.MixOpAndCFEnd;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Mix Op And CF End</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class MixOpAndCFEndImpl extends AbstractEndImpl implements MixOpAndCFEnd
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MixOpAndCFEndImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ECModelPackage.Literals.MIX_OP_AND_CF_END;
  }

} //MixOpAndCFEndImpl
