/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.edgecloudmodel.eCModel.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.edgecloudmodel.eCModel.ECModelPackage;
import org.xtext.example.edgecloudmodel.eCModel.OclTypeCS;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Ocl Type CS</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class OclTypeCSImpl extends ReservedKeywordCSImpl implements OclTypeCS
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OclTypeCSImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ECModelPackage.Literals.OCL_TYPE_CS;
  }

} //OclTypeCSImpl
