/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.edgecloudmodel.eCModel.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.edgecloudmodel.eCModel.ECModelPackage;
import org.xtext.example.edgecloudmodel.eCModel.RightSubAtomicExpression;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Right Sub Atomic Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RightSubAtomicExpressionImpl extends MinimalEObjectImpl.Container implements RightSubAtomicExpression
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RightSubAtomicExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ECModelPackage.Literals.RIGHT_SUB_ATOMIC_EXPRESSION;
  }

} //RightSubAtomicExpressionImpl
