/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.edgecloudmodel.eCModel.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.edgecloudmodel.eCModel.ECModelPackage;
import org.xtext.example.edgecloudmodel.eCModel.StandardNoneParameterOperation;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Standard None Parameter Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class StandardNoneParameterOperationImpl extends PredefineOpImpl implements StandardNoneParameterOperation
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StandardNoneParameterOperationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ECModelPackage.Literals.STANDARD_NONE_PARAMETER_OPERATION;
  }

} //StandardNoneParameterOperationImpl
