/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.edgecloudmodel.eCModel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Call Exp CS</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.edgecloudmodel.eCModel.ECModelPackage#getCallExpCS()
 * @model
 * @generated
 */
public interface CallExpCS extends LeftSubAtomicExpression, RightSubAtomicExpression
{
} // CallExpCS
