/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.edgecloudmodel.eCModel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Collection Type CS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.edgecloudmodel.eCModel.CollectionTypeCS#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.edgecloudmodel.eCModel.CollectionTypeCS#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.edgecloudmodel.eCModel.ECModelPackage#getCollectionTypeCS()
 * @model
 * @generated
 */
public interface CollectionTypeCS extends TypeCS
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' containment reference.
   * @see #setName(CollectionTypeIdentifierCS)
   * @see org.xtext.example.edgecloudmodel.eCModel.ECModelPackage#getCollectionTypeCS_Name()
   * @model containment="true"
   * @generated
   */
  CollectionTypeIdentifierCS getName();

  /**
   * Sets the value of the '{@link org.xtext.example.edgecloudmodel.eCModel.CollectionTypeCS#getName <em>Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' containment reference.
   * @see #getName()
   * @generated
   */
  void setName(CollectionTypeIdentifierCS value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(TypeCS)
   * @see org.xtext.example.edgecloudmodel.eCModel.ECModelPackage#getCollectionTypeCS_Type()
   * @model containment="true"
   * @generated
   */
  TypeCS getType();

  /**
   * Sets the value of the '{@link org.xtext.example.edgecloudmodel.eCModel.CollectionTypeCS#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(TypeCS value);

} // CollectionTypeCS
