/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.edgecloudmodel.eCModel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Collection Type Identifier CS</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.edgecloudmodel.eCModel.ECModelPackage#getCollectionTypeIdentifierCS()
 * @model
 * @generated
 */
public interface CollectionTypeIdentifierCS extends ReservedKeywordCS
{
} // CollectionTypeIdentifierCS
