/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.edgecloudmodel.eCModel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Enum Literal Exp CS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.edgecloudmodel.eCModel.EnumLiteralExpCS#getEnumname <em>Enumname</em>}</li>
 *   <li>{@link org.xtext.example.edgecloudmodel.eCModel.EnumLiteralExpCS#getEunmitem <em>Eunmitem</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.edgecloudmodel.eCModel.ECModelPackage#getEnumLiteralExpCS()
 * @model
 * @generated
 */
public interface EnumLiteralExpCS extends LiteralExpCS
{
  /**
   * Returns the value of the '<em><b>Enumname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enumname</em>' attribute.
   * @see #setEnumname(String)
   * @see org.xtext.example.edgecloudmodel.eCModel.ECModelPackage#getEnumLiteralExpCS_Enumname()
   * @model
   * @generated
   */
  String getEnumname();

  /**
   * Sets the value of the '{@link org.xtext.example.edgecloudmodel.eCModel.EnumLiteralExpCS#getEnumname <em>Enumname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Enumname</em>' attribute.
   * @see #getEnumname()
   * @generated
   */
  void setEnumname(String value);

  /**
   * Returns the value of the '<em><b>Eunmitem</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Eunmitem</em>' attribute.
   * @see #setEunmitem(String)
   * @see org.xtext.example.edgecloudmodel.eCModel.ECModelPackage#getEnumLiteralExpCS_Eunmitem()
   * @model
   * @generated
   */
  String getEunmitem();

  /**
   * Sets the value of the '{@link org.xtext.example.edgecloudmodel.eCModel.EnumLiteralExpCS#getEunmitem <em>Eunmitem</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Eunmitem</em>' attribute.
   * @see #getEunmitem()
   * @generated
   */
  void setEunmitem(String value);

} // EnumLiteralExpCS
