/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.edgecloudmodel.eCModel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Execution End</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.edgecloudmodel.eCModel.ExecutionEnd#getExecution <em>Execution</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.edgecloudmodel.eCModel.ECModelPackage#getExecutionEnd()
 * @model
 * @generated
 */
public interface ExecutionEnd extends MixEnd
{
  /**
   * Returns the value of the '<em><b>Execution</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Execution</em>' reference.
   * @see #setExecution(Execution)
   * @see org.xtext.example.edgecloudmodel.eCModel.ECModelPackage#getExecutionEnd_Execution()
   * @model
   * @generated
   */
  Execution getExecution();

  /**
   * Sets the value of the '{@link org.xtext.example.edgecloudmodel.eCModel.ExecutionEnd#getExecution <em>Execution</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Execution</em>' reference.
   * @see #getExecution()
   * @generated
   */
  void setExecution(Execution value);

} // ExecutionEnd
