/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.edgecloudmodel.eCModel;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fork Node</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.edgecloudmodel.eCModel.ForkNode#getStartlinks <em>Startlinks</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.edgecloudmodel.eCModel.ECModelPackage#getForkNode()
 * @model
 * @generated
 */
public interface ForkNode extends WorkflowExp
{
  /**
   * Returns the value of the '<em><b>Startlinks</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.edgecloudmodel.eCModel.JoinExp}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Startlinks</em>' reference list.
   * @see org.xtext.example.edgecloudmodel.eCModel.ECModelPackage#getForkNode_Startlinks()
   * @model
   * @generated
   */
  EList<JoinExp> getStartlinks();

} // ForkNode
