/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.edgecloudmodel.eCModel;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Interaction</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.edgecloudmodel.eCModel.Interaction#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.edgecloudmodel.eCModel.Interaction#getParticipants <em>Participants</em>}</li>
 *   <li>{@link org.xtext.example.edgecloudmodel.eCModel.Interaction#getMessages <em>Messages</em>}</li>
 *   <li>{@link org.xtext.example.edgecloudmodel.eCModel.Interaction#getExecutions <em>Executions</em>}</li>
 *   <li>{@link org.xtext.example.edgecloudmodel.eCModel.Interaction#getCombinedFragments <em>Combined Fragments</em>}</li>
 *   <li>{@link org.xtext.example.edgecloudmodel.eCModel.Interaction#getEnds <em>Ends</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.edgecloudmodel.eCModel.ECModelPackage#getInteraction()
 * @model
 * @generated
 */
public interface Interaction extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.edgecloudmodel.eCModel.ECModelPackage#getInteraction_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.edgecloudmodel.eCModel.Interaction#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Participants</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.edgecloudmodel.eCModel.Participant}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Participants</em>' reference list.
   * @see org.xtext.example.edgecloudmodel.eCModel.ECModelPackage#getInteraction_Participants()
   * @model
   * @generated
   */
  EList<Participant> getParticipants();

  /**
   * Returns the value of the '<em><b>Messages</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.edgecloudmodel.eCModel.Message}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Messages</em>' containment reference list.
   * @see org.xtext.example.edgecloudmodel.eCModel.ECModelPackage#getInteraction_Messages()
   * @model containment="true"
   * @generated
   */
  EList<Message> getMessages();

  /**
   * Returns the value of the '<em><b>Executions</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.edgecloudmodel.eCModel.Execution}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Executions</em>' containment reference list.
   * @see org.xtext.example.edgecloudmodel.eCModel.ECModelPackage#getInteraction_Executions()
   * @model containment="true"
   * @generated
   */
  EList<Execution> getExecutions();

  /**
   * Returns the value of the '<em><b>Combined Fragments</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.edgecloudmodel.eCModel.CombinedFragment}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Combined Fragments</em>' containment reference list.
   * @see org.xtext.example.edgecloudmodel.eCModel.ECModelPackage#getInteraction_CombinedFragments()
   * @model containment="true"
   * @generated
   */
  EList<CombinedFragment> getCombinedFragments();

  /**
   * Returns the value of the '<em><b>Ends</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.edgecloudmodel.eCModel.AbstractEnd}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ends</em>' containment reference list.
   * @see org.xtext.example.edgecloudmodel.eCModel.ECModelPackage#getInteraction_Ends()
   * @model containment="true"
   * @generated
   */
  EList<AbstractEnd> getEnds();

} // Interaction
