/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.edgecloudmodel.eCModel;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Join Node</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.edgecloudmodel.eCModel.JoinNode#getEndlinks <em>Endlinks</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.edgecloudmodel.eCModel.ECModelPackage#getJoinNode()
 * @model
 * @generated
 */
public interface JoinNode extends WorkflowExp
{
  /**
   * Returns the value of the '<em><b>Endlinks</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.edgecloudmodel.eCModel.JoinExp}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Endlinks</em>' reference list.
   * @see org.xtext.example.edgecloudmodel.eCModel.ECModelPackage#getJoinNode_Endlinks()
   * @model
   * @generated
   */
  EList<JoinExp> getEndlinks();

} // JoinNode
