/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.edgecloudmodel.eCModel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Loop Exp CS</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.edgecloudmodel.eCModel.ECModelPackage#getLoopExpCS()
 * @model
 * @generated
 */
public interface LoopExpCS extends CallExpCS
{
} // LoopExpCS
