/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.edgecloudmodel.eCModel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Null Literal Exp CS</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.edgecloudmodel.eCModel.ECModelPackage#getNullLiteralExpCS()
 * @model
 * @generated
 */
public interface NullLiteralExpCS extends PrimitiveLiteralExpCS
{
} // NullLiteralExpCS
