/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.edgecloudmodel.eCModel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Number Literal Exp CS</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.edgecloudmodel.eCModel.ECModelPackage#getNumberLiteralExpCS()
 * @model
 * @generated
 */
public interface NumberLiteralExpCS extends PrimitiveLiteralExpCS
{
} // NumberLiteralExpCS
