/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.edgecloudmodel.eCModel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Primitive Type CS</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.edgecloudmodel.eCModel.ECModelPackage#getPrimitiveTypeCS()
 * @model
 * @generated
 */
public interface PrimitiveTypeCS extends TypeCS, ReservedKeywordCS
{
} // PrimitiveTypeCS
