/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.edgecloudmodel.eCModel;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Service</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.edgecloudmodel.eCModel.Service#getOperation <em>Operation</em>}</li>
 *   <li>{@link org.xtext.example.edgecloudmodel.eCModel.Service#getTemp_property <em>Temp property</em>}</li>
 *   <li>{@link org.xtext.example.edgecloudmodel.eCModel.Service#getWorkflow <em>Workflow</em>}</li>
 *   <li>{@link org.xtext.example.edgecloudmodel.eCModel.Service#getInvariance <em>Invariance</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.edgecloudmodel.eCModel.ECModelPackage#getService()
 * @model
 * @generated
 */
public interface Service extends Participant
{
  /**
   * Returns the value of the '<em><b>Operation</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.edgecloudmodel.eCModel.Operation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operation</em>' containment reference list.
   * @see org.xtext.example.edgecloudmodel.eCModel.ECModelPackage#getService_Operation()
   * @model containment="true"
   * @generated
   */
  EList<Operation> getOperation();

  /**
   * Returns the value of the '<em><b>Temp property</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.edgecloudmodel.eCModel.Attribute}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Temp property</em>' containment reference list.
   * @see org.xtext.example.edgecloudmodel.eCModel.ECModelPackage#getService_Temp_property()
   * @model containment="true"
   * @generated
   */
  EList<Attribute> getTemp_property();

  /**
   * Returns the value of the '<em><b>Workflow</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.edgecloudmodel.eCModel.Workflow}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Workflow</em>' reference list.
   * @see org.xtext.example.edgecloudmodel.eCModel.ECModelPackage#getService_Workflow()
   * @model
   * @generated
   */
  EList<Workflow> getWorkflow();

  /**
   * Returns the value of the '<em><b>Invariance</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.edgecloudmodel.eCModel.Invariance}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Invariance</em>' containment reference list.
   * @see org.xtext.example.edgecloudmodel.eCModel.ECModelPackage#getService_Invariance()
   * @model containment="true"
   * @generated
   */
  EList<Invariance> getInvariance();

} // Service
