/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.edgecloudmodel.eCModel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Standard None Parameter Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.edgecloudmodel.eCModel.ECModelPackage#getStandardNoneParameterOperation()
 * @model
 * @generated
 */
public interface StandardNoneParameterOperation extends PredefineOp
{
} // StandardNoneParameterOperation
