/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.edgecloudmodel.eCModel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variable Declaration CS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.edgecloudmodel.eCModel.VariableDeclarationCS#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.edgecloudmodel.eCModel.VariableDeclarationCS#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.example.edgecloudmodel.eCModel.VariableDeclarationCS#getInitExpression <em>Init Expression</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.edgecloudmodel.eCModel.ECModelPackage#getVariableDeclarationCS()
 * @model
 * @generated
 */
public interface VariableDeclarationCS extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.edgecloudmodel.eCModel.ECModelPackage#getVariableDeclarationCS_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.edgecloudmodel.eCModel.VariableDeclarationCS#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(TypeCS)
   * @see org.xtext.example.edgecloudmodel.eCModel.ECModelPackage#getVariableDeclarationCS_Type()
   * @model containment="true"
   * @generated
   */
  TypeCS getType();

  /**
   * Sets the value of the '{@link org.xtext.example.edgecloudmodel.eCModel.VariableDeclarationCS#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(TypeCS value);

  /**
   * Returns the value of the '<em><b>Init Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Init Expression</em>' containment reference.
   * @see #setInitExpression(OCLExpressionCS)
   * @see org.xtext.example.edgecloudmodel.eCModel.ECModelPackage#getVariableDeclarationCS_InitExpression()
   * @model containment="true"
   * @generated
   */
  OCLExpressionCS getInitExpression();

  /**
   * Sets the value of the '{@link org.xtext.example.edgecloudmodel.eCModel.VariableDeclarationCS#getInitExpression <em>Init Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Init Expression</em>' containment reference.
   * @see #getInitExpression()
   * @generated
   */
  void setInitExpression(OCLExpressionCS value);

} // VariableDeclarationCS
