/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.edgecloudmodel.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.edgecloudmodel.parser.antlr.internal.InternalECModelParser;
import org.xtext.example.edgecloudmodel.services.ECModelGrammarAccess;

public class ECModelParser extends AbstractAntlrParser {

	@Inject
	private ECModelGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalECModelParser createParser(XtextTokenStream stream) {
		return new InternalECModelParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "RequirementModel";
	}

	public ECModelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ECModelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
